version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "infra"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "infra"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "infra"
